name: Deploy to GitHub Pages

on:
  push:
    branches: [main]          # run whenever main is updated
  workflow_dispatch:          # allows you to trigger manually if needed

permissions:
  contents: write             # so the action can push to gh-pages
  pages: write                # only needed if you ever switch to Pages APIs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣  Check out the repository
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣  Set up Node (use the same version as your dev environment)
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣  Cache npm dependencies for faster builds
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      # 4️⃣  Install, build, and test
      - name: Install deps
        run: npm ci                # deterministic install
      - name: Build
        run: npm run build         # outputs to dist/

      # 5️⃣  Deploy the dist/ folder to gh-pages branch
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Optional: keep commit history small
          keep_files: false
